## tensor basic

In [1]:
import torch

- 1 -> 스칼라, 모양은 []
- [1,2,3] -> 벡터, 모양은 [3]
- [[1,2,3]] -> 행렬, 모양은 [[1,3]]
- [[[1,2,3]]] -> n랭크 텐서, [1,1,3]

In [2]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [3]:
## 랭크 늘리기
x = torch.unsqueeze(x,0)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [4]:
## 랭크 줄이기
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [5]:
## 직접 랭크 모양 수정하기[3,3]->[9]
x = x.view(9)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: torch.Size([9])
Shape: torch.Size([9])
랭크(차원): 1


In [6]:
try:
    x = x.view(2,4)
except Exception as e:
    print(e) #error 출력

shape '[2, 4]' is invalid for input of size 9


## tensor operation

In [7]:
w = torch.randn(5,3, dtype = torch.float)
x = torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
print("w size:", w.size()) #[5,3]
print("x size:", x.size()) #[3,2]
print("w:",w)
print("x:",x)

w size: torch.Size([5, 3])
x size: torch.Size([3, 2])
w: tensor([[ 0.5607, -0.4729, -2.2407],
        [-0.1827,  1.5310, -1.1534],
        [-1.2531, -1.1118, -1.4243],
        [-1.5190,  0.2427,  1.5574],
        [ 0.7624,  0.4797,  0.7442]])
x: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [8]:
b = torch.randn(5,2, dtype = torch.float)
print("b.size:", b.size()) #[5,2]
print("b:",b)

b.size: torch.Size([5, 2])
b: tensor([[-0.9343,  1.0504],
        [ 0.4638,  0.1871],
        [-0.3930,  1.1864],
        [ 0.7504,  0.3117],
        [-0.9675, -0.6875]])


In [9]:
### 내적
wx = torch.mm(w,x) 
print("wx size:", wx.size()) #[5,2]
print("wx:",wx)

wx size: torch.Size([5, 2])
wx: tensor([[-12.0617, -14.2147],
        [ -1.3564,  -1.1615],
        [-11.7102, -15.4995],
        [  6.9963,   7.2775],
        [  5.9227,   7.9091]])


In [10]:
result = wx+b
print("result size:", result.size())
print("result:", result)

result size: torch.Size([5, 2])
result: tensor([[-12.9961, -13.1643],
        [ -0.8926,  -0.9744],
        [-12.1032, -14.3130],
        [  7.7467,   7.5892],
        [  4.9552,   7.2216]])
